// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmwohbwgjazmmhadplgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtd29oYndnamF6bW1oYWRwbGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4MTMzNTMsImV4cCI6MjA3NzM4OTM1M30.1hMgYFLmTAQ6Mkccx_S2vxYU0_Cm4QU4JPoNoKXKhq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});